project:
  type: website
  render:
    - why.qmd
    - how.qmd
    - sec-1-1-overview.qmd
    - sec-1-2-examples.qmd
    - sec-3-2-Logit.qmd
    - sec-3-3-Logit-AUC-ROC.qmd
    # - Ch-2-EDA-vis.qmd
    # - Ch-3-LM.qmd
    # - Ch-3-VarSele.qmd
    - about.qmd
    
website:
  title: "Data Mining for Business Analytics"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Preface"
        contents:
          - href: why.qmd
          - how.qmd
      - section: "1 Data Mining"
        contents:
          - sec-1-1-overview.qmd
          - sec-1-2-examples.qmd
      # - section: "2 Exploratory Data Analysis"
      #   contents:
      #     - Ch-2-EDA-vis.qmd
      - section: "3 Supervised Data Mining"
        contents:
          # - Ch-3-LM.qmd
          - sec-3-2-Logit.qmd
          - sec-3-3-Logit-AUC-ROC.qmd
          # - Ch-3-VarSele.qmd
      - section: "About"
        contents:
          - about.qmd
  google-analytics: "G-PFYV0SJVTC"
  open-graph: true

resources: 
  - CRAME
format:
  html:
    theme: 
      light: Litera
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 310px

editor: source
execute: 
  freeze: false
