project:
  type: website
  render:
    - why.qmd
    - how.qmd
    - overview.qmd
    - about.qmd
    
website:
  title: "Data Mining for Business Analytics"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Preface"
        contents:
          - href: why.qmd
          - how.qmd
      - section: "1 Data Mining"
        contents:
          - overview.qmd
      - section: "About"
        contents:
          - about.qmd
  google-analytics: "G-PFYV0SJVTC"
  open-graph: true

format:
  html:
    theme: 
      light: Litera
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px

editor: source
execute: 
  freeze: auto
